export CPU_ARCH = cortex-m4f
export CPU_FAM  = stm32f4

USEMODULE += pm_layered

# include common periph module
USEMODULE += periph_eth

include $(RIOTCPU)/stm32_common/Makefile.include
include $(RIOTMAKE)/arch/cortexm.inc.mk
